misspelled_words_dict = {
    "acommodate": "accommodate",
    "definately": "definitely",
    "recieve": "receive",
    "occured": "occurred",
    "seperate": "separate",
    "goverment": "government",
    "thier": "their",
    "untill": "until",
    "suprise": "surprise",
    "truely": "truly",
    "wierd": "weird",
    "beleive": "believe",
    "concious": "conscious",
    "adress": "address",
    "arguement": "argument",
    "acheive": "achieve",
    "calender": "calendar",
    "consistant": "consistent",
    "recomend": "recommend",
    "existance": "existence",
    "harrass": "harass",
    "ocassion": "occasion",
    "priviledge": "privilege",
    "remeber": "remember",
    "tommorow": "tomorrow",
    "vacume": "vacuum",
    "independant": "independent",
    "maintainance": "maintenance",
    "neccessary": "necessary",
    "ocurrance": "occurrence",
    "publically": "publicly",
    "rediculous": "ridiculous",
    "resistence": "resistance",
    "supercede": "supersede",
    "twelth": "twelfth",
    "wich": "which",
    "writting": "writing",
    "embarass": "embarrass",
    "millenium": "millennium",
    # Correctly spelled words
    "accommodate": "accommodate",
    "receive": "receive",
    "government": "government",
    "separate": "separate",
    "address": "address",
    "conscious": "conscious",
    "recommend": "recommend",
    "necessary": "necessary",
    "independent": "independent",
    "occurrence": "occurrence",
    "privilege": "privilege",
    "definitely": "definitely",
    "tomorrow": "tomorrow",
    "calendar": "calendar",
    "vacuum": "vacuum",
    "supersede": "supersede"
}

# Sentences containing misspelled words
misspelled_sentences_dict = {
    "I will acommodate your request as best as I can.": "accommodate",
    "She will definatelly attend the meeting tomorrow.": "definitely",
    "They will recive the package by noon.": "receive",
    "The event occured last week without any issues.": "occurred",
    "Make sure to seperate the recyclables from the trash.": "separate",
    "The goverment announced a new policy today.": "government",
    "I believe that thier proposal is very effective.": "their",
    "We won't be there untill after lunch.": "until",
    "What a suprise to see you here!": "surprise",
    "He is truely an amazing person.": "truly",
    "That sounds a bit wierd to me.": "weird",
    "I can't beleive she won the contest!": "believe",
    "Being concious of your actions is important.": "conscious",
    "Can you please adress the issues raised?": "address",
    "The arguement escalated quickly.": "argument",
    "I need to acheive my goals this year.": "achieve",
    "The calender shows we have a meeting next week.": "calendar",
    "It is important to be consistant in your efforts.": "consistent",
    "I would like to recomend this book.": "recommend",
    "The existance of aliens is a popular topic.": "existence",
    "They try to harrass me whenever they can.": "harass",
    "There is a special ocassion coming up.": "occasion",
    "It's a great priviledge to work with you.": "privilege",
    "Don't forget to remeber your keys!": "remember",
    "We'll see you tommorow at the same time.": "tomorrow",
    "The vacuum is broken again.": "vacuum",
    "An independant study was conducted last year.": "independent",
    "The maintainance of the equipment is crucial.": "maintenance",
    "This task is neccessary for the project.": "necessary",
    "The most recent ocurrance of that event was last month.": "occurrence",
    "The event will be publically announced next week.": "publicly",
    "That was a rediculous thing to say!": "ridiculous",
    "The resitence of the material was tested thoroughly.": "resistance",
    "Don't forget to supercede the old files with the new ones.": "supersede",
    "She lives on the twelth floor.": "twelfth",
    "I don't know wich book to choose.": "which",
    "I enjoy writting in my journal every night.": "writing",
    "It can be embarass to forget someone's name.": "embarrass",
    "The new millenium brought many changes.": "millennium",
}
